### ISSUE TITLE
Duplicate name in Iliad test file 

### ISSUE THREAD

**Issue by tofuness** [thorehusfeldt/algdes-labs#3]
See these lines:

https://github.com/thorehusfeldt/algdes-labs/blob/582532c9142a884c8faf1d9c0ec788b2b089cd88/matching/data/sm-illiad-in.txt#L57

https://github.com/thorehusfeldt/algdes-labs/blob/582532c9142a884c8faf1d9c0ec788b2b089cd88/matching/data/sm-illiad-in.txt#L103

**Comment by thorehusfeldt** [comment]
Interesting. I don’t think this is a problem for actually running the lab, but it certainly makes it less fun. I need to consult my original code for producing this.

**Comment by thorehusfeldt** [comment]
Aha! We don’t know our classics, it seems. There are (of course) two different Laodices. One is the loveliest daughter of Priam, King of Troy. The other is a daughter of Agamemnon, leader of the Greeks.

Note the same at all.
